apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-deployment
  namespace: optit-lab-python 

spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-hello
      tier: frontend
  template:
    metadata:
      labels:
        app: flask-hello
        tier: frontend
    spec:
      containers:
        - name: flask-hello
          image: raorajath/flask-hello-world:pythonlatest  
          ports:
            - containerPort: 8585
              name: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
