apiVersion: v2
kind: Service
metadata:
  name: flask-hello-world-devops-project-service
  namespace: optit-lab-python
spec:
  selector:
    app: flask-hello
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 8585
  
