apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service-nodeport
  namespace: optit-lab-python  # Specify the namespace here

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
  selector:
    app: flask-hello
    tier: frontend
